version: '3.8'
services:
  db:
    image: postgres:16
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    ports:
      - '5432:5432'
    volumes:
      - ecom_pgdata:/var/lib/postgresql/data
volumes:
  ecom_pgdata:
